### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by 89z** [softcoder24/insta_share#8]
Using this program:

~~~py
from insta_share import Instagram
insta = Instagram()
insta.login('srpen6', 'PASSWORD')
~~~

I get this result:

~~~
Traceback (most recent call last):
  File "D:\Desktop\ig.py", line 5, in <module>
    insta.login('srpen6', 'PASSWORD')
  File "C:\python\lib\site-packages\insta_share\instagram.py", line 21, in login
    csrf = response.cookies['csrftoken']
  File "C:\python\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\python\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
~~~

**Comment by softcoder24** [comment]
Actually, still, there is a problem with the login function. But once you get the credentials for the first time you can use them for other tasks like posting.

**Comment by 89z** [comment]
I solved this using a request like this:

~~~
POST /api/v1/accounts/login/ HTTP/1.1
Host: i.instagram.com
Content-Type: application/x-www-form-urlencoded
User-Agent: Instagram 207.0.0.39.120 Android

signed_body=SIGNATURE.{"device_id":"Instagram 207.0.0.39.120 Android",
"enc_password":"#PWD_INSTAGRAM:0:0:yourPassword","username":"yourUsername"}
~~~

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/tree/master/instagram

**Comment by oluca** [comment]
Have a look at my solution, maybe it helps: [https://github.com/softcoder24/insta_share/issues/9](https://github.com/softcoder24/insta_share/issues/9)
